"""Clean baseline

Revision ID: 5d4718e340f7
Revises: 
Create Date: 2025-11-24 15:31:59.685145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4718e340f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title_template', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('generation_mode', sa.String(), nullable=True))
    op.alter_column('tasks', 'recurrence_weekday',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('client_id', sa.INTEGER(), nullable=True))
    op.add_column('tasks', sa.Column('created_by', sa.INTEGER(), nullable=False))
    op.add_column('tasks', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tasks', 'clients', ['client_id'], ['id'])
    op.alter_column('tasks', 'recurrence_weekday',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'generation_mode')
    op.drop_column('tasks', 'title_template')
    # ### end Alembic commands ###
